export const FAQDATA = [
    {
        id:0, title: "When Can I Get the Vaccine?", content:"We are currently in Phase 1B tiers 3 and 4. See the visual timeline below for more information about who is eligible right now. Due to an initial limited supply of vaccine, there is not enough right now to offer it to everyone. This means we had to make tough decisions about who gets the vaccine first. This is called vaccine allocation and prioritization. So far, three COVID-19 vaccines are authorized for emergency use by the FDA. There are also several other vaccines being developed and tested",
    },
    {
        id:1, title: "Where Can I Get the Vaccine?", content:"You can use our App to find the closest provider in your zipcode. Or visit https://vaccinelocator.doh.wa.gov/.",
    },
    {
        id:2, title: "How can I Get the COVID-19 Vaccine?", content:"First, Determine if you are eligible by using the eligibilty test on our App. Second, If you are eligible, use our Vaccine Provider Locator to find a vaccine near you. Finally, Schedule your appointment and follow the clinic's instructions. Not eligible yet? Your turn will be soon!",
    },
    {
        id:3, title: "What are the benefits of getting Vaccinated?", content:"The COVID-19 vaccines help protect people in these ways: 1)They can greatly reduce your chance of getting seriously ill, even if you get COVID-19, 2)Completing the vaccine series reduces your chances of hospitalization and lowers your risk of dying from COVID-19,    3)They are highly effective at preventing COVID-19, 4)They add to the number of people in the community who are protected from getting COVID-19 — making it harder for the disease to spread. And Experts continue to conduct more studies about the ability of the vaccine to keep people from spreading the virus to others",
    },
    {
        id:4, title: "How do the COVID-19 Vaccines work?", content:"Their are two types. The MRNA vaccine and Viral vector vaccine. Two of the vaccines authorized by the FDA are messenger RNA (mRNA) vaccines. MRNA vaccines teach your cells to produce a harmless piece of the coronavirus spike protein that then triggers an immune response to build antibodies. In this way, you build immunity to COVID-19 without getting the illness.Both mRNA vaccines are two dose vaccines. It typically takes about two weeks after the second dose to become fully protected. One of the COVID-19 vaccines authorized by the FDA is a viral vector vaccine. Vector vaccines contain a weakened version of a virus—a different virus than the one that causes COVID-19—that teaches your cells to make a harmless piece of coronavirus spike protein. Your immune system sees that the protein shouldn’t be there, which triggers your body to make antibodies that remember how to fight that virus if you are infected with COVID-19 in the future.The vector vaccine we have available is a one dose vaccine. It typically takes about two weeks after you get the vaccine to become fully protected. Sometimes vaccination can cause mild fever or cold-like symptoms, but these are not harmful. ",
    },
    {
        id:5, title: "What is the Washington State COVID-19 Vaccination Plan?", content:"The COVID-19 vaccine is here in Washington. All of the vaccines authorized for emergency use by the FDA are currently being distributed across the state. The Centers for Disease Control and Prevention (CDC) required all states and territories to turn in an interim plan for COVID-19 vaccine distribution on Oct. 16, 2020. These plans are living documents and will change over time as we learn more about the vaccines and figure out the most equitable way to protect people.",
    },
    {//Vaccine Distribution FAQ
        id:6, title: "How will vaccine distribution work?", content:"The CDC primarily will manage the distribution of COVID-19 vaccine. The current plan is to distribute the vaccine through two mechanisms:1)Use of a centralized distributor. 2)Direct shipments to Indian Health Services clinics; pharmacy chains; and large multi-state healthcare systems.As part of this planning effort, the federal government and the state are considering many factors such as prioritization of high-risk groups, vaccine supply and distribution, logistics, safety, and clinical guidance. Because the current top three vaccine candidates all require different temperatures, properly transporting and storing the vaccine at the right temperature is a large concern and big part of the planning. Vaccine distribution will adjust over time as the number of available doses increases, moving from limited to broader populations in a phased approach.",
    },
    {
        id:7, title: "Who are the DOH partners in Washington state?", content:"Since there are numerous decisions to make, we are engaging and coordinating with tribal nations, local government, community leaders, and others partners to develop and implement vaccination efforts. We are doing this because: 1)We need input on prioritization of the initial doses of vaccine, and how to best distribute it.2)We want to support vaccinators in being ready to vaccinate the initial priority groups. ",
    },
    {//Allocation FAQs
        id:8, title: "How do you determine which providers get vaccines each week?", content:"The CDC sets aside a specific number of COVID-19 vaccine doses for each state to distribute, called allocation. Right now, Washington state is not getting enough first and second doses to meet demand. We have to decide how to distribute, or allocate, this limited supply to providers across the state.We ask all vaccine providers to complete a weekly REDCap allocation survey. The survey tells us how many doses providers are seeking for the following week. To decide how to distribute vaccine, we consider: 1)County population size, 2)Populations that each provider serves and how that relates to who is eligible for vaccines. 3)Each provider’s inventory on hand, how many vaccines they administer and how quickly, and success reporting data to the state on time. And 4)number of doses the provider has received in the past.These factors help us decide how to best distribute vaccine across the state. However, supply is limited right now and there is not enough vaccine to go around. We also must ensure that people across the state and in high-risk groups have equitable access to the vaccine. Vaccine providers must fill out the allocation survey every week as accurately as possible. Because supply is limited, filling out the survey does not guarantee that we can give providers the amount of vaccine they ask for. The survey helps us understand providers’ need and capacity, which informs future allocation decisions.",
    },
    {
        id:9, title: "When does DOH know how much COVID-19 vaccine Washington will get each week?", content:"The CDC tells us on Tuesdays how much vaccine we will get for the following week. The federal government now also gives us a 3-week allocation forecast. This is an estimate of how many first and second doses we should expect in the next three weeks. However, the forecast may change if the federal government’s supply changes.",
    },
    {
        id:10, title: "How do providers order vaccine for the next week?", content:"Providers place vaccine orders in the state Immunization Information System (IIS). They should request the number of first and second doses they can give in 7 days.Ordering in the IIS is open between Friday at 5:00 p.m. and Monday at 5:00 p.m. Vaccine arrives the next Monday or Tuesday, one week after ordering.In addition to ordering in the IIS, providers must complete the weekly REDCap survey. This helps DOH decide how to allocate vaccine.",
    },
    {//Planning FAQs
        id:11, title: "How have you planned for the COVID-19 vaccine?", content:"We've been working with the federal government and local partners within Washington to plan for the distribution of a COVID-19 vaccine. We turned in our interim vaccine distribution plan to the CDC on October 16, 2020.On October 29, 2020, the CDC released version 2 of the COVID-19 Vaccination Program Interim Playbook for Jurisdiction Operations.The second update of our plan included changes guided by the CDC’s new playbook along with other sources of feedback.",
    },
    {
        id:12, title: "Has DOH received federal funding for COVID-19 vaccine distribution?", content:"Yes. We have received $5 million in federal funding for COVID-19 vaccine response preparation. This funding will support partnerships with local health jurisdictions and tribal entities, mass vaccination clinics, vendor contracts, and staffing. The department has redirected some current staff to this program and is hiring additional positions to support this work.",
    },
    {
        id:13, title: "What other kinds of information are you gathering?", content:"We've conducted focus groups and key interviews with disproportionately impacted communities, workers, and business sectors throughout October. Key groups include African American/Black communities, Latinx community, Pacific Islander communities, immigrant and refugee communities, older adults, people experiencing homelessness, farmworkers, people with underlying health conditions, and individuals with disabilities.We have also engaged with communities and sectors who are at higher risk for getting or spreading COVID-19. This includes essential workers and businesses, health care workers and providers, college students, youth, early learning providers, and parents.",
    },
    {//Availability FAQs
        id:14, title: "I’ve completed the COVID-19 vaccine series. If I’m exposed to COVID-19, do I need to quarantine?", content:"No, fully vaccinated people do not need to quarantine or be tested if exposed to someone with COVID-19 as long as they show no signs of illness. However, you should still monitor yourself for any COVID-19 symptoms for 14 days after you are exposed.If you do start having symptoms, you should isolate yourself and contact your health care provider. Tell them you’ve been vaccinated before seeking out testing or evaluation.",
    },
    {
        id:15, title: "Can people under age 18 get the vaccine?", content:"Yes. People ages 16 and over can get the Pfizer-BioNTech vaccine when they are eligible.  Youth who are 16 or 17 years of age may need consent from a parent or guardian to get the vaccine, unless they are legally emancipated.Check with the vaccine clinic about their requirements for showing proof of parental consent or legal emancipation.",
    },
    {
        id:16, title: "Will everyone in Washington be able to get the COVID-19 vaccine?", content:"Due to an initial limited supply of vaccine, we do not have enough right now to offer it to everyone. This means we had to make tough decisions about who gets the vaccine first. This is called vaccine allocation and prioritization. Eventually there will be enough vaccine for everyone who wants it.Two federal groups lead recommendations for vaccine prioritization:The National Academies of Sciences, Engineering, and MedicineThe CDC's Advisory Committee on Immunization Practices (ACIP).On Friday, October 2, the National Academy of Medicine released the “Framework for Equitable Allocation of COVID-19 Vaccine” consensus study report. We are using this report to guide our planning along with guidance from ACIP, who began voting on interim recommendations in a special session on December 1.We are working on finalizing our vaccine allocation and prioritization framework, which is also guided by feedback from the communities, partners, sectors, and industries that are heavily impacted by COVID-19 in Washington state. ",
    },
    {//General FAQs
        id:17, title: "I’ve had COVID-19. Can I get the vaccine?", content:"Yes, the Advisory Committee on Immunization Practices (ACIP) recommends anyone who previously had COVID-19 to get the vaccine.Data shows it is uncommon to be re-infected with COVID-19 in the 90 days after you were infected, so you might have some protection (called natural immunity). However, we don't know how long natural immunity might last.People who currently have COVID-19 should wait to get vaccinated until they feel better and their isolation period is finished, if possible.People who were recently exposed to COVID-19 should also wait to get the vaccine until after their quarantine period, if they can safely quarantine away from other people. If there is a high risk they could infect others, they may be vaccinated during their quarantine period to prevent spreading the disease.",
    },
    {
        id:18, title: "Can I get the COVID-19 vaccine if I’m pregnant, lactating or planning to become pregnant?", content:"Yes. People who are pregnant may choose to get the vaccine any time. People who are lactating, or planning to get pregnant may choose to get the COVID-19 vaccine when they are eligible in the current vaccine phase.The American College of Obstetricians and Gynecologists (ACOG) and the Centers for Disease Control and Prevention (CDC) recommend you talk with your health care provider about whether the vaccine is right for you. While safety data on the use of COVID-19 vaccine in pregnant people is limited, the information we have is reassuring.  If you would like to speak to someone about getting the COVID-19 vaccine during pregnancy, please contact MotherToBaby. MotherToBaby experts are available to content titles in English or Spanish by phone or chat. The free and confidential service is available Monday to Friday 8 a.m. to 5 p.m. (local time). To reach MotherToBaby:Call 1-866-626-6847",
    },
    {
        id:19, title: "Do I qualify for the vaccine if I work in a school or child care setting?", content:"Yes. On March 2, 2021, President Biden announced a directive to get teachers and licensed child care workers vaccinated. His goal is for each teacher and child care worker to get at least one dose of COVID-19 vaccine by the end of March. The Washington State Department of Health has followed this directive and expanded it to ensure equitable access in our state. We have now added to the current group of people who can get vaccinated:Pre-kindergarten through 12th grade staffAll child care workers, whether licensed or not These groups can get vaccinated at any available location with any brand of available vaccine. ",
    },
    {
        id:20, title: "Where do school or child care employees find available vaccine?", content:"School and child care workers may get the vaccine at any location convenient for them, but we recommend first using the ZipCode search to find a Federal Retail Pharmacy Partnership location. Demand for vaccine is currently very high, and it may take a while to get an appointment at other locations.Many local pharmacies are receiving additional supply from the government through the Federal Retail Pharmacy Partnership (FRPP) to support teachers and child care workers in Washington. More doses are expected to come in every week to help meet this increase in demand. These convenient locations currently include select Albertsons, Kroger, Costco, Rite Aid, Walmart and HealthMart pharmacies. Search participating locations near you. Available supply is updated online daily at these locations, so check back often for updates.",
    },
    {
        id:21, title: "Can I get the COVID-19 vaccine when I get routine vaccinations?", content:"There is limited data on whether it is safe and effective to get the Pfizer-BioNTech, Moderna or Johnson & Johnson – Janssen COVID-19 vaccines with other vaccines. At this time, the COVID-19 vaccine should be given alone, at least 14 days (2 weeks) before or after you get any other type of vaccine.",
    },
    {
        id:22, title: "If I get a COVID-19 vaccine, do I still need to take other precautions?", content:"Yes, even if you get vaccinated, we recommend you continue to wear a mask, wash your hands often, stay six feet apart, and limit gatherings. Many people in our state will need to wait months to get the vaccine, and these prevention measures are recommended to help prevent the spread of COVID-19 to people who are not yet vaccinated.The COVID-19 vaccines work well, but they are not 100% effective. Some people may get COVID-19 even if they’ve been vaccinated. Vaccine studies have focused mainly on whether the vaccine keeps you from getting COVID-19; they haven’t looked as much into whether the vaccine prevents you from spreading it to others. Until we know more, please continue your prevention measures. We also want to remind you that it’s not too late to get your flu vaccine. Adults with or without insurance can get flu vaccine at no cost this year.",
    },
    {//Adminstration & Supplies
        id:23, title: "Can any pharmacy, clinic, or hospital offer the COVID-19 vaccine?", content:"o receive and administer the COVID-19 vaccine and supplies, providers must enroll in a federal vaccine distribution program, coordinated through the state immunization program (unless they are part of a national chain that registered directly with the CDC). The federal government will procure and distribute the vaccine at no cost to enrolled providers.On October 27, the department sent an official letter from Secretary of Health, John Weisman and Health Officer, Dr. Kathy Lofy, to health care providers about how they can enroll as COVID-19 vaccine providers.On November 2, we opened enrollment for the COVID-19 Vaccination Program. The department encourages more clinics, pharmacies, hospitals, and health care offices enroll. In addition, on October 16, the White House announced a federal partnership with CVS and Walgreens to administer the COVID-19 vaccine to residents and staff in long-term care facilities.",
    },
    {
        id:24, title: "Do I have to be a U.S. citizen to get the vaccine?", content:"No, you do not need to be a U.S. citizen to get the vaccine. That means you do not need a social security number, or other documents with your immigration status, to get the vaccine. Some vaccine providers might ask for a social security number, but you do not have to give one.",
    },
    {
        id:25, title: "Do I have to show my ID to get the vaccine in Washington?", content:"Given our state’s limited supply of vaccine, and our commitment to equitable and fair vaccine access, you must live or work in Washington to get vaccinated at our state-run mass vaccination clinics (Ridgefield, Spokane, Kennewick, and Wenatchee).We recognize the desire to get vaccinated and know that neighboring states are also giving vaccinations. If you do not live or work in Washington, please do not make vaccine appointments or travel to Washington mass vaccination clinics for vaccines. People who register for vaccines at these four sites may be asked to show one of the following: 1)Driver's license or work/school ID, 2)Letter with your address, 3) Utility bill, 4)Statement/letter with a Washington state address or 5)Voucher from an employer, faith-based institution, health care provider, school, or other registered organization or agency, etc. that the person lives or works in Washington state. The vaccine site will not make a copy or record this information in any way. This is only to show that you live or work in Washington state.",
    },
    {
        id:26, title: "What is a vaccine administration fee?", content:"The vaccine administration fee is the fee a health care provider charges to give you the vaccine. This is separate from the cost of the vaccine itself. ",
    },
    {
        id:27, title: "Who pays for the vaccine administration fee?", content:"The federal government will pay for the full cost of the vaccine. If you have public or private health insurance, your vaccine provider may bill them to get reimbursed for the vaccine administration fee. If you do not have insurance, the federal government offers a program that will pay the provider to administer your vaccination.You should not be charged out of pocket costs or receive a bill from your provider for the COVID-19 vaccine administration fee. This applies to people who have private insurance, have Apple Health (Medicaid), have Medicare, or are uninsured. ",
    },
    {
        id:28, title: "Why am I being asked to show my insurance card?", content:"When you get the vaccine, your vaccine provider may ask if you have an insurance card. This is so they can get reimbursed for giving you the vaccine (vaccine administration fee). Let your provider know if you do not have insurance. You will still be able to get the vaccine at no-cost.",
    },
    {
        id:29, title: "What if I don’t have an insurance card?", content:"If you do not have insurance coverage, tell your provider. You will still get the vaccine at no-cost. The federal government has a program that will pay the provider to administer your vaccination. ",
    },
    {
        id:30, title: "What about office visit fees?", content:"You should not be charged for an office visit if you only receive the vaccine. If other services are performed along with the administration of the vaccine, it may be billed as an office visit. Seek clarification from your provider beforehand and from your insurance company if you are charged an office visit fee.",
    },
    {
        id:31, title: "I received a bill from my provider for the COVID-19 vaccine or the vaccine administration fee. What do I do?", content:"If you have health insurance, contact your insurance plan first. If this doesn’t address the issue, you can also file a complaint with the Office of the Insurance Commissioner. If you do not have health insurance, remember that providers are not allowed to charge you for the vaccine and therefore may be violating the requirements of the COVID-19 vaccine program. Please email covid.vaccine@doh.wa.gov.",
    },
    {
        id:32, title: "Do I have to get both doses of the COVID-19 vaccine?", content:"The Pfizer and Moderna vaccines are both two doses. If you get either the Pfizer or Moderna vaccine, you will need to get your second dose to get maximum protection against COVID-19.The Johnson & Johnson-Janssen COVID-19 vaccine is a single-dose vaccine. You do not need to go back for a second dose. ",
    },
    {
        id:33, title: "Will the COVID-19 vaccine be mandatory?", content:"It will be your choice whether to get the vaccine for COVID-19. Washington is not currently considering any mandates for the vaccine, but employers could require it. The vaccine will help protect you and others around you from getting COVID-19, and we encourage you to talk to your doctor or clinic about the benefits.",
    },
    {
        id:34, title: "What supplies will come with the vaccine kits?", content:"Supply kits will include vaccine record cards, alcohol swabs, syringes, limited personal protective equipment (PPE), and similar items needed to administer a vaccine.",
    },
    {
        id:35, title: "What is the Federal Retail Pharmacy Program for COVID-19 Vaccination?", content:"This program is a partnership between the federal government and 21 national pharmacy chains and independent pharmacy networks. The purpose is to help bring COVID-19 vaccine to communities across the United States. Over time, the program will include over 40,000 retail locations nationwide. The program launched in early February 2021. Participating pharmacies in Washington state include: Albertsons Companies, Inc.,Costco Wholesale Corp.,Health Mart Pharmacies,Kroger Co.,Rite Aid Pharmacies,Walmart Inc.,Check the pharmacy website to find out if they offer COVID-19 vaccine in your community. Please note that early on, your local pharmacy may not have vaccine, or may have limited supply.",
    },
    {
        id:36, title: "What is a vaccination record card?", content:"You should receive a paper vaccination record card when you get your first dose of COVID-19 vaccine. This card will tell you which type of vaccine you got (Pfizer-BioNTech, Moderna, or Johnson & Johnson) and the date you received it.If you got the Pfizer-BioNTech or Moderna vaccine, the card will tell you when to go back for your second dose. Keep this card with you so your vaccine provider can complete it after your second dose.The Johnson & Johnson vaccine is one dose, so you will not need to schedule a follow-up. Some people find it helpful to take a photo of the card as a backup. If you lose your record card, log in to MyIR (“My Immunization Registry”), https://wa.myir.net/login/,  to look up your COVID-19 vaccination record, and then take a screenshot or photo of the information. If you do not have an account, you can sign up for MyIR any time. https://wa.myir.net/login/",
    },
    { //Covid-19 Vaccines FAQs
        id:37, title: "How do we know the vaccines are safe?", content:"Researchers collected safety and efficacy data as part of the Phase III clinical trials in the U.S. and other countries. A combined total of over 115,000 volunteers participated in the clinical trials for the Pfizer-BioNTech, Moderna, and Johnson & Johnson – Janssen COVID-19 vaccines.Before the vaccines became available here in Washington, the federal Advisory Committee on Immunization Practices conducted a review to ensure they could safely recommend the vaccines and for which populations. In addition, the western states Scientific Safety Review Workgroup gave input on vaccine safety and efficacy. Both groups voted to recommend the Pfizer-BioNTech COVID-19 vaccine for people over 16 years of age, and the Moderna and Johnson & Johnson – Janssen COVID-19 vaccines to people 18 years and older. ",
    },
    {
        id:38, title: "How will a COVID-19 vaccine work in my body?", content:"The COVID-19 vaccine teaches your immune system to recognize the coronavirus. When you get the vaccine, your immune system makes antibodies (“fighter cells”) that stay in your blood and protect you in case you are infected with the virus. You get protection against the disease without having to get sick.When enough people in the community can fight off the coronavirus, it has nowhere to go. This means we can stop the spread quicker and get a little closer to ending this pandemic.",
    },
    {
        id:39, title: "How are COVID-19 vaccines made?", content:"This short video explains how the COVID-19 Vaccine is made.https://www.youtube.com/watch?v=HqsmhCJurTM",
    },
    {
        id:40, title: "What is an mRNA vaccine?", content:"A messenger RNA, or mRNA vaccine is a new type of vaccine. mRNA vaccines teach your cells how to make a harmless piece of the “spike protein.” The spike protein is what you see on the surface of the coronavirus. Your immune system sees that the protein doesn’t belong there and your body will start to build an immune response and make antibodies. This is similar to what happens when we “naturally” get a COVID-19 infection.Although we have used mRNA for other types of medical and veterinary care in the past, creating vaccines using this method is a huge leap forward in science and may mean future vaccines can be created more easily.",
    },
    {
        id:41, title: "What is a viral vector vaccine?", content:"This type of vaccine uses a weakened version of a different virus (the “vector”) that gives your cells instructions. The vector enters a cell and uses the cell’s machinery to create a harmless piece of the COVID-19 spike protein. The cell displays the spike protein on its surface, and your immune system sees that it doesn’t belong there. Your immune system will start to make antibodies and activate other immune cells to fight off what it thinks is an infection. Your body learns how to protect you against future infection with COVID-19, without you having to get sick.",
    },
    {
        id:42, title: "What types of symptoms are normal after receiving the vaccines?", content:"Like other routine vaccines, the most common side effects are a sore arm, fatigue, headache, and muscle pain.These symptoms are a sign that the vaccine is working. In the Pfizer and Moderna trials, these side effects occurred most often within two days of getting the vaccine, and lasted about a day. Side effects were more common after the second dose than the first dose. In the Johnson & Johnson clinical trials, side effects lasted an average of one to two days. For all three vaccines, people over 55 were less likely to report side effects than younger people.",
    },
    {
        id:43, title: "What types of symptoms are normal after receiving the Pfizer vaccine?", content:"Clinical trials found that approximately: Eighty percent of people reported pain at the injection site. Fifty percent of people reported fatigue and headache.Thirty percent of people reported muscle pain.",
    },
    {
        id:44, title: "What types of symptoms are normal after receiving the Moderna vaccine?", content:"Clinical trials found that approximately: Ninety percent of people reported pain at the injection site. Seventy percent of people reported fatigue and headache. Sixty percent of people reported muscle pain.",
    },
    {
        id:45, title: "What types of symptoms are normal after receiving the Johnson & Johnson vaccine?", content:"Clinical trials found that approximately: Sixty percent of people reported pain at the injection site. Forty-five percent of people reported fatigue and headache. Forty percent of people reported muscle pain. ",
    },
    {
        id:46, title: "What about the rumors of the Vaccine's side effects?", content:"You may see some rumors about untrue side effects online or on social media. Make sure any time you see a claim about a side effect that you check the source of that claim.",
    },
    {
        id:47, title: "What ingredients are in the vaccines?", content:"You may see some rumors and untrue ingredients listed online or in social media. These are generally myths. The ingredients in the COVID-19 vaccines are pretty typical for vaccines. They contain the active ingredient of mRNA or modified adenovirus along with other ingredients like fat, salts, and sugars that protect the active ingredient, help it work better in the body, and protect the vaccine during storage and transport. You can find the full ingredients lists in the Pfizer, Moderna, and Johnson & Johnson fact sheets. Pfizer's can be found at http://www.cvdvaccine.com/ . Moderna's can be found at http://www.modernatx.com/covid19vaccine-eua. Johnson & Johnson can be found at http://www.janssencovid19vaccine.com/",
    },
    {
        id:48, title: "Does the Johnson & Johnson vaccine contain fetal tissue?", content:"The Johnson & Johnson COVID-19 vaccine was created using the same technology as many other vaccines. It does not contain parts of fetuses or fetal cells. One piece of the vaccine is made in lab-grown copies of cells that originally came from elective abortions that took place over 35 years ago. Since then, the cell lines for these vaccines have been maintained in the lab and no further sources of fetal cells are used to make these vaccines. This might be new information for some people. However, vaccines for chickenpox, rubella and hepatitis A are made in the same way.",
    },
    {
        id:49, title: "Does the COVID-19 vaccine cause infertility?", content:"This is a myth circulated online by non-scientific sources. There is no evidence that fertility problems are a side effect of any vaccine, including COVID-19 vaccines. According to the  American College of Obstetricians and Gynecologists (ACOG), anyone who may want to get pregnant in the future can get the COVID-19 vaccine.",
    },
    {
        id:50, title: "What is an Emergency Use Authorization? (EUA)", content:"An EUA allows the FDA to make a product available during a declared state of emergency before it has a full license. Any EUA granted by the FDA is further vetted by the Scientific Safety Review Workgroup, as part of the Western States Pact.",
    },
    {
        id:51, title: "What is the Western States Pact?", content:"On October 27, Gov. Jay Inslee announced Washington is joining other western states to review the safety and efficacy of COVID-19 vaccines once approved by the FDA. The Scientific Safety Review Workgroup includes Washington, Oregon, Nevada, Colorado and California. Inslee announced Washington’s representatives to the workgroup on Nov. 9. The panel will include experts appointed by all member states, and nationally recognized scientists with expertise in immunization and public health. They will review all publicly available data concurrently with federal reviews, and will present a report as soon as possible after the FDA grants an Emergency Use Authorization (EUA) for a vaccine. This will happen for all COVID-19 vaccines that are granted an EUA. The process is expected to take about 1 to 2 days and be completed before the first vaccine shipment arrives in Washington, so it will not delay the processThe department has engaged with communities and groups that are most impacted by COVID-19, and we have heard that Washington communities have questions and concerns about the safety of the vaccine. We want to give our community the highest confidence. The Scientific Safety Review Workgroup will provide another layer of scrutiny and expert review to this process.",
    },
    {
        id:52, title: "Is it COVID-19 or a vaccine reaction?", content:"COVID-19 vaccination commonly comes with side effects, such as sore muscles or a fever. If you have symptoms after getting the vaccine, you may wonder if it’s safe to work or go about your tasks safely. Employers may wonder if it’s safe for a staff member to return to in-person work. It can take 1-2 weeks after your second shot before you are fully protected so you could still come down with COVID-19 if you are exposed before then. It’s also important to remember that each person’s immune system works a little differently and the vaccine won’t work for approximately 1 in 2500 people who are vaccinated. ",
    },
    {
        id:53, title: "Can I get the COVID-19 vaccine if I’ve had an allergic reaction to a vaccine in the past?", content:"The vaccine should not be given to people with a known history of severe allergic reaction, such as anaphylaxis, to a previous dose of an mRNA or viral vector vaccine, or to any ingredient of the Pfizer-BioNTech, Moderna, or Johnson & Johnson–Janssen COVID-19 vaccines.People who have had a severe allergic reaction to other vaccines or injectable therapies may still be able to receive the vaccine. However, providers should do a risk assessment and counsel them about potential risks. If the patient decides to get the vaccine, the provider should observe them for 30 minutes to monitor for any immediate reactions.The Advisory Committee on Immunization Practices (ACIP) recommends that providers observe all other patients for at least 15 minutes after receiving the vaccine to monitor for an allergic reaction",
    },
    {
        id:54, title: "Can I choose which Vaccine to get?", content:"You should get any COVID-19 vaccine that is available when you are eligible. Do not wait for a specific brand. All currently authorized and recommended COVID-19 vaccines are safe and effective, and CDC does not recommend one vaccine over another.",
    },
    {
        id:55, title: "How long does protection from a COVID-19 Vaccine last?", content:"We don’t know how long protection lasts for those who are vaccinated. What we do know is that COVID-19 has caused very serious illness and death for a lot of people. If you get COVID-19, you also risk giving it to loved ones who may get very sick. Getting a COVID-19 vaccine is a safer choice.Experts are working to learn more about both natural immunity and vaccine-induced immunity. CDC will keep the public informed as new evidence becomes available.",
    },
    {
        id:56, title: "Do I need to wear a mask & avoid close contact with others if I have received 2 doses of the vaccine?", content:"It depends. For now, fully vaccinated people can gather indoors without physical distancing or wearing masks with:Other people who are fully vaccinated, Unvaccinated people from one other household, unless any of those people or anyone they live with has an increased risk for severe illness from COVID-19. Until more is known, fully vaccinated people should continue to wear masks and stay 6 feet apart from other people in other settings, like when they are in public or visiting with unvaccinated people from multiple households.",
    },
    {
        id:57, title: "If I have already had COVID-19 and recovered, do I still need to get vaccinated with a COVID-19 Vaccine?", content:"Yes, you should be vaccinated regardless of whether you already had COVID-19. That’s because experts do not yet know how long you are protected from getting sick again after recovering from COVID-19. Even if you have already recovered from COVID-19, it is possible—although rare—that you could be infected with the virus that causes COVID-19 again.If you were treated for COVID-19 with monoclonal antibodies or convalescent plasma, you should wait 90 days before getting a COVID-19 vaccine. Talk to your doctor if you are unsure what treatments you received or if you have more questions about getting a COVID-19 vaccine.Experts are still learning more about how long vaccines protect against COVID-19 in real-world conditions. CDC will keep the public informed as new evidence becomes available.",
    },
    {
        id:58, title: "Who is paying for the COVID-19 Vaccine?", content:"The federal government is providing the vaccine free of charge to all people living in the United States, regardless of their immigration or health insurance status.COVID-19 vaccination providers cannot: 1)Charge you for the vaccine, 2)Charge you directly for any administration fees, copays, or coinsurance, 3)Deny vaccination to anyone who does not have health insurance coverage, is underinsured, or is out of network, 4)Charge an office visit or other fee to the recipient if the only service provided is a COVID-19 vaccination, 5)Require additional services in order for a person to receive a COVID-19 vaccine; however, additional healthcare services can be provided at the same time and billed as appropriate. COVID-19 vaccination providers can: 1)Seek appropriate reimbursement from the recipient’s plan or program (e.g., private health insurance, Medicare, Medicaid) for a vaccine administration fee.However, providers cannot charge the vaccine recipient the balance of the bill,2)Seek reimbursement for uninsured vaccine recipients from the Health Resources and Services Administration’s COVID-19 Uninsured Program.",
    },
    {
        id:59, title: "How many doses of the COVID-19 vaccine will I need to receive?", content:"The number of doses needed depends on which vaccine you receive. To get the most protection:Two Pfizer-BioNTech vaccine doses should be given 3 weeks (21 days) apart. Two Moderna vaccine doses should be given 1 month (28 days) apart. Johnson & Johnsons Jansen (J&J/Janssen) COVID-19 vaccine requires only one dose. If you receive a vaccine that requires two doses, you should get your second shot as close to the recommended interval as possible. However, your second dose may be given up to 6 weeks (42 days) after the first dose, if necessary.. You should not get the second dose earlier than the recommended interval. ",
    },
    {
        id:60, title: "If I have an underlying condition, can I get the COVID-19 Vaccine?", content:"People with underlying medical conditions can receive a COVID-19 vaccine as long as they have not had an immediate or severe allergic reaction to a COVID-19 vaccine or to any of the ingredients in the vaccine. Learn more about vaccination considerations for people with underlying medical conditions from your provider. Vaccination is an important consideration for adults of any age with certain underlying medical conditions because they are at increased risk for severe illness from COVID-19. ",
    },
    {
        id:61, title: "Can I get vaccinated against COVID-19 while I am currently sick with COVID-19?", content:"No. People with COVID-19 who have symptoms should wait to be vaccinated until they have recovered from their illness and have met the criteria for discontinuing isolation; those without symptoms should also wait until they meet the criteria before getting vaccinated. This guidance also applies to people who get COVID-19 before getting their second dose of vaccine. ",
    }

]